apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: guestbook-secret
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: forge-dso
  path: forge-mi/projects/mi/demo2/guestbook
  destination:
    create: true
    name: guestbook-secret
