apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: secret-hack
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: forge-dso
  path: forge-mi/projects/mi/arno/GITLAB
  destination:
    create: true
    name: secret-hack
